#gt915 touchpanel driver

ifneq ($(CONFIG_TCT_8X26_COMMON), y)
obj-$(CONFIG_GT9XX_TOUCHPANEL_DRIVER)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_GT9XX_TOUCHPANEL_UPDATE)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_GT9XX_TOUCHPANEL_DEBUG)	+= goodix_tool.o
endif
