ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ flash/ eeprom/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor.o
obj-$(CONFIG_S5K3L1YX) += s5k3l1yx.o
obj-$(CONFIG_IMX135) += imx135.o
obj-$(CONFIG_IMX134) += imx134.o
obj-$(CONFIG_OV8825) += ov8825.o
obj-$(CONFIG_OV8865) += ov8865.o
obj-$(CONFIG_s5k4e1) += s5k4e1.o
obj-$(CONFIG_OV12830) += ov12830.o
obj-$(CONFIG_OV2720) += ov2720.o
obj-$(CONFIG_OV9724) += ov9724.o
obj-$(CONFIG_HI256) += hi256.o
obj-$(CONFIG_OV5648) += ov5648.o
obj-$(CONFIG_MT9M114) += mt9m114.o
obj-$(CONFIG_SP1628) += sp1628.o
obj-$(CONFIG_GC0339) += gc0339.o
obj-$(CONFIG_OV8865) += ov8865.o
# [PLATFORM]-Mod-BEGIN by TCTNB.HJ, 2013/08/31, CAM dev
obj-$(CONFIG_OV5648_MIATA_TCT) += ov5648_miata_v4l2_tct.o
obj-$(CONFIG_OV5648_RIO5_CTCC_TCT) += ov5648_rio5_ctcc_v4l2_tct.o
obj-$(CONFIG_OV5648FF_RIO4G_TCT) += ov5648ff_rio4g_v4l2_tct.o
obj-$(CONFIG_OV5648_RIO4G_TCT) += ov5648_rio4g_v4l2_tct.o
obj-$(CONFIG_OV5648_RIO4G_2ND_TCT) += ov5648_rio4g_2nd_v4l2_tct.o
obj-$(CONFIG_S5K4H5YC_EOS_TCT) += s5k4h5yc_eos_v4l2_tct.o
obj-$(CONFIG_S5K4H5YC_OLD_EOS_TCT) += s5k4h5yc_old_eos_v4l2_tct.o
obj-$(CONFIG_S5K4H5YC_MIATA_TCT) += s5k4h5yc_miata_v4l2_tct.o
obj-$(CONFIG_S5K4H5YC_OLD_MIATA_TCT) += s5k4h5yc_old_miata_v4l2_tct.o
obj-$(CONFIG_S5K4H5YC_RIO6_TCT) += s5k4h5yc_rio6_v4l2_tct.o
obj-$(CONFIG_S5K4H5YC_OLD_RIO6_TCT) += s5k4h5yc_old_rio6_v4l2_tct.o
obj-$(CONFIG_OV8858_EOS_TCT) += ov8858_eos_v4l2_tct.o
obj-$(CONFIG_OV8858_RIO6_TCT) += ov8858_rio6_v4l2_tct.o
obj-$(CONFIG_OV8858_MIATA_TCT) += ov8858_miata_v4l2_tct.o
obj-$(CONFIG_S5K5E2_RIO5_CTCC_TCT) += s5k5e2_rio5_ctcc_v4l2_tct.o
obj-$(CONFIG_GC0339_TCT) += gc0339_v4l2_tct.o
# [PLATFORM]-Add-BEGIN by TCTNB.WPL, 2013/12/10, refer to bug564642
obj-$(CONFIG_GC0339_RIO5_CTCC_TCT) += gc0339_rio5_ctcc_v4l2_tct.o
# [PLATFORM]-Add-END by TCTNB.WPL, 2013/12/10
obj-$(CONFIG_GC0313_TCT) += gc0313_v4l2_tct.o
# [PLATFORM]-Mod-END by TCTNB.HJ, 2013/08/31
# [PLATFORM]-Add-BEGIN by TCTNB.WPL, 2013/10/22, refer to bug514151
obj-$(CONFIG_GC2035_MIATA_TCT) += gc2035_miata_v4l2_tct.o
# [PLATFORM]-Add-END by TCTNB.WPL, 2013/10/22
# [PLATFORM]-Add-BEGIN by TCTNB.WPL, 2014/01/02, 2nd sub CAM GC2035 dev, refer to bug580548
obj-$(CONFIG_GC2035_RIO6_TCT) += gc2035_rio6_v4l2_tct.o
# [PLATFORM]-Add-END by TCTNB.WPL, 2014/01/02
# [PLATFORM]-Add-BEGIN by TCTNB.WPL, 2013/11/29, refer to bug549457
obj-$(CONFIG_HI258_RIO6_TCT) += hi258_rio6_v4l2_tct.o
# [PLATFORM]-Add-END by TCTNB.WPL, 2013/11/29
# [PLATFORM]-Add-BEGIN by TCTNB.WPL, 2013/12/11, add for miata 2nd sub camera, refer to bug569866
obj-$(CONFIG_HI258_MIATA_TCT) += hi258_miata_v4l2_tct.o
# [PLATFORM]-Add-END by TCTNB.WPL, 2013/12/11
# [PLATFORM]-Mod-BEGIN by TCTNB.WPL, 2013/12/06, EOS sub CAM sunny & sinetech s5k8aay, refer to bug529375 & bug565601
obj-$(CONFIG_S5K8AAY_TCT) += s5k8aay_sunny_v4l2_tct.o
obj-$(CONFIG_S5K8AAY_TCT) += s5k8aay_sinetech_v4l2_tct.o
# [PLATFORM]-Mod-END by TCTNB.WPL, 2013/11/07
#Begin add by weicai.long@tcl.com, 2013/1/13.
obj-$(CONFIG_HI258_POP7LTE) += hi258_pop7lte.o
obj-$(CONFIG_GC2035_SHINETECH) += gc2035_shinetech.o
obj-$(CONFIG_GC0339_POP7LTE) += gc0339_pop7lte.o
obj-$(CONFIG_GC0339_SUNRISE_POP7LTE) += gc0339_sunrise_pop7lte.o
#End add by weicai.long@tcl.com, 2013/1/13.
